# Generated by Django 5.0.3 on 2025-03-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('number_of_people', models.IntegerField()),
                ('arrival_date', models.DateField()),
                ('leaving_date', models.DateField()),
            ],
        ),
    ]
