# Generated by Django 5.0.3 on 2025-03-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='destination',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
    ]
