# Generated by Django 5.1.7 on 2025-03-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Sydney', 'Sydney'), ('Hawaii', 'Hawaii'), ('Spiti Valley', 'Spiti Valley'), ('Chandratal', 'Chandratal'), ('Vietnam', 'Vietnam'), ('Mount Fuji', 'Mount Fuji'), ('Himalayas', 'Himalayas'), ('Goa', 'Goa'), ('Rome', 'Rome')], default='Mumbai', max_length=255),
        ),
    ]
