# Generated by Django 5.1.7 on 2025-03-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_amount_booking_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
    ]
